name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          script: sh test/Node-React-App/deploy.sh
    
