name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd server
      - run: pm2 start app.js

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MY_KEY }}
          REMOTE_HOST: 54.209.182.99
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/Node-React-App/
